code --install-extension abusaidm.html-snippets
code --install-extension Angular.ng-template
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension fivethree.vscode-ionic-snippets
code --install-extension fknop.vscode-npm
code --install-extension formulahendry.auto-rename-tag
code --install-extension joelday.docthis
code --install-extension johnpapa.angular-essentials
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension Mikael.Angular-BeastCode
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-fr
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.debugger-for-edge
code --install-extension mutantdino.resourcemonitor
code --install-extension mwood0904.clear-console
code --install-extension natewallace.angular2-inline
code --install-extension nrwl.angular-console
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.LiveServer
code --install-extension RobbOwen.synthwave-vscode
code --install-extension rubiin.nestjs
code --install-extension VisualStudioExptTeam.vscodeintellicode
